API_KEY = "xBxAeqJeAZuDrh5gLLzk"
API_SECRET_KEY = "UYgkHUKzxMXEKi7SQyeN"
SUPPLIER_ID = "223116"
OPENAI_API_KEY = "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"  # Replace with your actual OpenAI key
